### ISSUE TITLE
404 https://github.com/libguestfs/guestfs-tools

### ISSUE THREAD

**Issue by SDRausty** [libguestfs/libguestfs-common#3]
https://github.com/libguestfs/guestfs-tools

404

Where is `guestfs-tools`?

**Comment by dvzrv** [comment]
@rwmjones how are releases for guestfs-tools created?

I'm packaging guestfs-tools for Arch Linux and without an upstream repository it is very complex for downstreams to track when there's a new release, if they can only rely on the [release directories](https://download.libguestfs.org/guestfs-tools/), which do not denote the specific versions.

**Comment by rwmjones** [comment]
The upstream repository is https://github.com/rwmjones/guestfs-tools .  This is "temporary" because we intend to move everything gitlab, but it's been like this for a couple of years so far because of delays and other issues with gitlab.

Tarballs are here: https://download.libguestfs.org/guestfs-tools/

**Comment by dvzrv** [comment]
Thanks for getting back on this topic! Hope you can figure out your issues with gitlab eventually :)
